/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdlib.h>
#include <stdio.h>

#include "1_1_ex_square.h"
#include "isshe_error.h"
#include "isshe_rpc.h"
/*
//注释掉的是自动生成的
void
square_prog_1( char* host )
{
	CLIENT *clnt;
	square_out  *result_1;
	square_in  squareproc_1_arg;
	clnt = clnt_create(host, SQUARE_PROG, SQUARE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = squareproc_1(&squareproc_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}


int main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		isshe_error_exit("usage: ./a.out <hostname> <integer-value>");
	}
	host = argv[1];
	square_prog_1( host );
	exit(0);
}
*/

int main(int argc, char *argv[])
{
    CLIENT *cl;
    square_in in;
    square_out *outp;

    if (3 != argc) {
        isshe_error_exit("usage: ./a.out <hostname> <integer-value>");
    }

    cl = isshe_clnt_create(argv[1], SQUARE_PROG, SQUARE_VERS, "tcp");

    in.arg1 = atol(argv[2]);
    if ( (outp = squareproc_1(&in, cl)) == NULL ) {
        isshe_error_exit("%s", clnt_sperror(cl, argv[1]));
    }

    printf("result: %ld\n", outp->res1);

    exit(0);
}
