/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "1_1_ex_square.h"

square_out *
squareproc_1_svc(square_in *argp, struct svc_req *rqstp)
{

	static square_out  result;

	/*
	 * insert server code here
	 */
	 result.res1 = argp->arg1 * argp->arg1;

	return(&result);
}
