# Generated by Django 2.2.6 on 2019-10-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topc', models.ForeignKey(on_delete=True, to='learning_log.Topic')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
